
name: Run Tests

on:
  push:
    branches: [ develop, main, feature/* ]
  pull_request:
    branches: [ develop, main, feature/* ]

permissions:
  id-token: write
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run_tests_and_code_coverage:
    name: Run Tests and Code Coverage
    runs-on: macos-14
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Select Xcode Version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.4.0'
      - name: Run Tests
        run: |
          swift test --enable-code-coverage






      # - name: Run Tests
      #   run: xcodebuild build test -project Example/KeychainPasswordStoreExample.xcodeproj -scheme KeychainPasswordStoreExample -destination 'platform=iOS Simulator,name=iPhone 14' -resultBundlePath /Users/runner/Library/Developer/Xcode/KeychainPasswordStore/ResultBundle/keychainPasswordStore_result
      # - name: Upload Xcode Code Coverage Report to CodeCov
      #   uses: codecov/codecov-action@v3
      #   with:
      #     fail_ci_if_error: true
      #     token: ${{ secrets.CODECOV_TOKEN }}
      #     verbose: true
      #     xcode: true
      #     xcode_archive_path: /Users/runner/Library/Developer/Xcode/KeychainPasswordStore/ResultBundle/keychainPasswordStore_result.xcresult